<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Leaseterms.aspx.cs" Inherits="Leaseterms" StylesheetTheme="Leaseterms"%>
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
     <form id="form1" runat="server">
     <h3 style="margin: 20px 0px 5px; padding: 0px; text-align: center; font-weight: bold; font-size: 12px; line-height: normal; color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
             <asp:HyperLink ID="HyperLink2" runat="server" Font-Bold="True" Font-Names="Gigi" Font-Size="XX-Large" style="text-align: center" Font-Underline="False" ForeColor="White" NavigateUrl="~/Main.aspx" Height="200px" ImageUrl="~/content/logo.gif" Width="400px" Text="CRC" >CRC</asp:HyperLink>
        </h3>
         <h3 style="margin: 20px 0px 5px; padding: 0px; text-align: center; font-weight: bold; font-size: 12px; line-height: normal; color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Airport Surcharge :</h3>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51); text-align: center; font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    Details are available from CRC Office.</p>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51);  text-align: center;font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Age :" style="text-decoration: none;  text-align: center; color: rgb(3, 107, 5); transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"><strong></strong></a><strong>Age :</strong></p>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51); text-align: center; font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    23, 25 or 28 years, according to the car group.</p>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51); text-align: center; font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Additional Driver :" style="text-decoration: none; text-align: center; color: rgb(3, 107, 5); transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"><strong></strong></a><strong>Additional Driver :</strong></p>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51); text-align: center; font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    With the consent of the renter, the vehicle may be driven by other persons. Conditions and possible charge available from CRC Office.</p>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51); text-align: center; font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Driving licence :" style="text-decoration: none; text-align: center; color: rgb(3, 107, 5); transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"><strong></strong></a><strong>Driving licence :</strong></p>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51); text-align: center; font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    Held for at least two years.</p>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51); text-align: center; font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Cash Rental deposit :" style="text-decoration: none;  text-align: center; color: rgb(3, 107, 5); transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"></a><strong>Cash Rental deposit :</strong></p>
<p style="margin: 0px 0px 15px; text-align: center; color: rgb(51, 51, 51);  font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    Details are available from CRC Office.</p>
<p style="margin: 0px 0px 15px; text-align: center; color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Credit Cards Accepted :" style="text-decoration: none; color: rgb(3, 107, 5);  text-align: center;transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"></a><strong>Credit Cards Accepted :</strong></p>
<p style="margin: 0px 0px 15px; text-align: center; color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    &nbsp;Mastercard, Visa.</p>
<p style="margin: 0px 0px 15px; text-align: center; color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Insurances :" style="text-decoration: none; text-align: center; color: rgb(3, 107, 5); transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"><strong></strong></a><strong>Insurances :</strong></p>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51); text-align: center; font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    PRO100 CASCO., Theft Protection : Charges may vary by station and by car group. Details are available from CRC Office.</p>
<p style="margin: 0px 0px 15px; color: rgb(51, 51, 51); text-align: center; font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Delivery / Collection" style="text-decoration: none; text-align: center; color: rgb(3, 107, 5); transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"><strong></strong></a><strong>Delivery / Collection</strong></p>
<p style="margin: 0px 0px 15px;text-align: center; color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    Only available Within City limits.</p>
<p style="margin: 0px 0px 15px; text-align: center;color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Other Services :" style="text-decoration: none; text-align: center;color: rgb(3, 107, 5); transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"><strong></strong></a><strong>Other Services :</strong></p>
<p style="margin: 0px 0px 15px; text-align: center;color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    Child Seat Baby, Child Seat Infant, Navigation System.</p>
<p style="margin: 0px 0px 15px; text-align: center;color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Restriction Of Use :" style="text-decoration: none;text-align: center; color: rgb(3, 107, 5); transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"></a><strong>Restriction Of Use :</strong></p>
<p style="margin: 0px 0px 15px; text-align: center;color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    Certain driving restrictions may apply for driving into certain countries. Details are available from CRC Office.</p>
<p style="margin: 0px 0px 15px;text-align: center; color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <a name="Chauffeur Driven Service :" style="text-decoration: none; text-align: center;color: rgb(3, 107, 5); transition: all 0.15s ease-out; cursor: pointer; font-family: Arial, Helvetica, Verdana, sans-serif; line-height: 16px; background-color: rgb(255, 255, 255);"><strong></strong></a><strong>Chauffeur Driven Service :</strong></p>
<p style="margin: 0px 0px 15px; text-align: center;color: rgb(51, 51, 51); font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; line-height: 16px;">
    Details are available from CRC Office.</p>
     </form>
    </body>
</html>
